### ISSUE TITLE
AdaCoreLegacyTestDriver does not always use self.default_encoding

### ISSUE THREAD

**Issue by glacambre** [AdaCore/e3-testsuite#125]
Dear e3-testsuite maintainer (😉),

Our [main testsuite's driver](https://gitlab.adacore-it.com/eng/codepeer/codepeer-tests/-/blob/master/tests/testsuite.py) is [inheriting from the AdaCoreLegacyTestDriver](https://gitlab.adacore-it.com/eng/codepeer/codepeer-tests/-/blob/master/tests/testsuite.py#L49) and overrides its self.default_encoding with `UTF-8`. This makes sense for our usecase, we do not deal with binary data but we do [deal with UTF-8 characters](https://gitlab.adacore-it.com/eng/codepeer/codepeer-tests/-/merge_requests/755#note_272661), hence having properly rendered UTF-8 characters is better than having `\x[0-F][0-F]` strings in our outputs.

Unfortunately, this [does not work well on windows](https://gaia.adacore.com/#/e/79686578/581-non-ascii-encoding-infer_run_wrapper__except1078), some of [our tests](https://gitlab.adacore-it.com/eng/codepeer/codepeer-tests/-/blob/master/tests/581-non-ascii-encoding-infer/test.sh) fail with the following backtrace:
```
Traceback (most recent call last):
  File "C:\it\sbx\wave\x86_64-windows64\e3-for-testing\install\lib\site-packages\e3\testsuite\fragment.py", line 187, in run
    self.return_value = self.data(self.previous_values, self.slot)
  File "C:\it\sbx\wave\x86_64-windows64\e3-for-testing\install\lib\site-packages\e3\testsuite\driver\classic.py", line 478, in run_wrapper
    self.set_up()
  File "C:\it\sbx\wave\x86_64-windows64\e3-for-testing\install\lib\site-packages\e3\testsuite\driver\adacore.py", line 91, in set_up
    self.argv = self.get_script_command_line()
  File "C:\it\sbx\wave\x86_64-windows64\e3-for-testing\install\lib\site-packages\e3\testsuite\driver\adacore.py", line 170, in get_script_command_line
    for line in f:
  File "C:\it\sbx\wave\x86_64-windows64\e3-for-testing\install\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 193: character maps to <undefined>
```

This is because the test.sh contains UTF-8 characters, but the AdaCoreLegacyTestDriver opens test.sh files using the platform's default encoding.

The following patch seems to make things work again:
```diff
diff --git "a/C:\\it\\local\\e3\\lib\\site-packages\\e3\\testsuite\\driver\\adacore.py" b/tmp/driver.py
index 8625a50c9..af3e01642 100644
--- "a/C:\\it\\local\\e3\\lib\\site-packages\\e3\\testsuite\\driver\\adacore.py"
+++ b/tmp/driver.py
@@ -164,7 +164,7 @@ class AdaCoreLegacyTestDriver(DiffTestDriver):
                 new_script.append(". $TEST_SUPPORT_DIR/support.sh")

             # Read all lines in the original test script
-            with open(self.script_file) as f:
+            with open(self.script_file, encoding=self.default_encoding) as f:
                 # Get rid of potential whitespaces and CR at the end of
                 # each line.
                 for line in f:
@@ -177,10 +177,10 @@ class AdaCoreLegacyTestDriver(DiffTestDriver):

             # Write the shell script and schedule its execution with "bash"
             new_script_filename = self.working_dir("__test.sh")
-            with open(new_script_filename, "w") as f:
+            with open(new_script_filename, "wb") as f:
                 for line in new_script:
-                    f.write(line)
-                    f.write("\n")
+                    f.write(line.encode(self.default_encoding))
+                    f.write(b"\n")
             return ["bash", new_script_filename]

         else:  # os-specific
```

Since I'm not sure I have a complete understanding of the situation, I thought I'd open an issue instead of a PR, let me know if you need more information :)

**Comment by glacambre** [comment]
Wrong repo.
